import dotenv from "dotenv";
import mongoose from "mongoose";
import mongooseConnect from "@/lib/mongooseConnect";
import User from "./User";
import Issue, { IIssue } from "./Issue";
import Table from "./Table";
import TableProperty from "./TableProperty";
import UserStory from "./UserStory";
import { getPopulatedIssues } from "./Controls";


async function seedTables() {

  await Table.deleteMany({});
  await TableProperty.deleteMany({});

  // User Table
  const user_table = await Table.create({name: "User"})
  await Promise.all([
    TableProperty.create({
      field: "user_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: user_table._id 
    }),
    TableProperty.create({
      field: "first_name",
      field_type: "Text",
      special: "Required",
      table: user_table._id 
    }),
    TableProperty.create({
      field: "last_name",
      field_type: "Text",
      special: "Required",
      table: user_table._id 
    }),
    TableProperty.create({
      field: "role",
      field_type: "Text",
      special: "Required, either “staff” or “admin”",
      table: user_table._id 
    }),
    TableProperty.create({
      field: "email",
      field_type: "Text",
      special: "Required",
      table: user_table._id 
    }),
    TableProperty.create({
      field: "email_verified_at",
      field_type: "Timestamp",
      special: "",
      table: user_table._id 
    }),
    TableProperty.create({
      field: "image_url",
      field_type: "Text",
      special: "",
      table: user_table._id 
    })
  ])


  // Paras Assigned To Case Managers Table
  const paras_to_cms_table = await Table.create({name: "Paras Assigned to Case Managers"});
  await Promise.all([
    TableProperty.create({
      field: "case_manager_id",
      field_type: "Unique ID",
      special: "Reference to 'user'",
      table: paras_to_cms_table._id 
    }),
    TableProperty.create({
      field: "para_id",
      field_type: "Unique ID",
      special: "Reference to 'user'",
      table: paras_to_cms_table._id 
    }),
  ])



  // Account Table
  const account_table = await Table.create({name: "Account"});
  await Promise.all([
    TableProperty.create({
      field: "account_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "user_id",
      field_type: "Unique ID",
      special: "Reference to “user”",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "provider_name",
      field_type: "Text",
      special: "Required",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "provider_account_id",
      field_type: "Text",
      special: "Required, unique combination with provider_name",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "access_token",
      field_type: "Text",
      special: ""
    }),
    TableProperty.create({
      field: "refresh_token",
      field_type: "Text",
      special: "",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "expires_at",
      field_type: "Integer",
      special: "",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "token_type",
      field_type: "Text",
      special: "",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "scope",
      field_type: "Text",
      special: "",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "id_token",
      field_type: "Text",
      special: "",
      table: account_table._id 
    }),
    TableProperty.create({
      field: "session_state",
      field_type: "Text",
      special: "",
      table: account_table._id 
    }),
  ])

  // Session Table
  const session_table = await Table.create({name: "Session"});
  await Promise.all([
    TableProperty.create({
      field: "session_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: session_table._id 
    }),
    TableProperty.create({
      field: "session_token",
      field_type: "Text",
      special: "Required, Unique",
      table: session_table._id 
    }),
    TableProperty.create({
      field: "user_id",
      field_type: "Text",
      special: "Required, reference to “user”",
      table: session_table._id 
    }),
    TableProperty.create({
      field: "expires_at",
      field_type: "Timestamp",
      special: "Required",
      table: session_table._id 
    }),
  ])


  // Student Table
  const student_table = await Table.create({name: "Student"});
  await Promise.all([
    TableProperty.create({
      field: "student_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: student_table._id 
    }),
    TableProperty.create({
      field: "first_name",
      field_type: "Text",
      special: "Required",
      table: student_table._id 
    }),
    TableProperty.create({
      field: "last_name",
      field_type: "Text",
      special: "Required",
      table: student_table._id 
    }),
    TableProperty.create({
      field: "email",
      field_type: "Text",
      special: "Required",
      table: student_table._id 
    }),
    TableProperty.create({
      field: "assigned_case_manager_id",
      field_type: "Timestamp",
      special: "References “user”",
      table: student_table._id 
    }),
    TableProperty.create({
      field: "grade",
      field_type: "Integer",
      special: "",
      table: student_table._id 
    }),
  ])


  // File Table
  const file_table = await Table.create({name: "File"});
  await Promise.all([
    TableProperty.create({
      field: "file_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: file_table._id 
    }),
    TableProperty.create({
      field: "name",
      field_type: "Text",
      special: "Required",
      table: file_table._id 
    }),
    TableProperty.create({
      field: "content_type",
      field_type: "Text",
      special: "Required",
      table: file_table._id 
    }),
    TableProperty.create({
      field: "ext_s3_path",
      field_type: "Text",
      special: "Required, either “staff” or “admin”",
      table: file_table._id 
    }),
    TableProperty.create({
      field: "uploaded_by_user_id",
      field_type: "Text",
      special: "Required",
      table: file_table._id 
    }),
    TableProperty.create({
      field: "created_at",
      field_type: "Timestamp",
      special: "Required, autogenerated",
      table: file_table._id 
    }),
  ])


  // Iep Table
  const iep_table = await Table.create({name: "Iep"});
  await Promise.all([
    TableProperty.create({
      field: "iep_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: iep_table._id 
    }),
    TableProperty.create({
      field: "student_id",
      field_type: "Unique ID",
      special: "References “student”",
      table: iep_table._id
    }),
    TableProperty.create({
      field: "case_manager_id",
      field_type: "Unique ID",
      special: "References “user”",
      table: iep_table._id
    }),
    TableProperty.create({
      field: "start_date",
      field_type: "Date",
      special: "Required",
      table: iep_table._id
    }),
    TableProperty.create({
      field: "end_date",
      field_type: "Date",
      special: "Required",
      table: iep_table._id
    }),
    TableProperty.create({
      field: "created_at",
      field_type: "Timestamp",
      special: "Required, autogenerated",
      table: iep_table._id
    }),
  ])


  // Goal Table
  const goal_table = await Table.create({name: "Goal"});
  await Promise.all([
    TableProperty.create({
      field: "goal_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: goal_table._id
    }),
    TableProperty.create({
      field: "iep_id",
      field_type: "Unique ID",
      special: "References “iep”",
      table: goal_table._id
    }),
    TableProperty.create({
      field: "description",
      field_type: "Text",
      special: "Required",
      table: goal_table._id
    }),
    TableProperty.create({
      field: "category",
      field_type: "Text",
      special: "Required, either 'writing', 'reading', 'math', or 'other'",
      table: goal_table._id
    }),
    TableProperty.create({
      field: "created_at",
      field_type: "Timestamp",
      special: "Required, autogenerated",
      table: goal_table._id
    }),
  ])


  // Subgoal Table
  const subgoal_table = await Table.create({name: "Subgoal"});
  await Promise.all([
    TableProperty.create({
      field: "subgoal_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "goal_id",
      field_type: "Unique ID",
      special: "References “goal”",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "status",
      field_type: "Text",
      special: "Either “In Progress” or “Complete”",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "description",
      field_type: "Text",
      special: "Required",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "setup",
      field_type: "Text",
      special: "Required",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "instructions",
      field_type: "Text",
      special: "Required",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "materials",
      field_type: "Text",
      special: "Required",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "target_level",
      field_type: "Integer",
      special: "Required (between 0 and 100)",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "baseline_level",
      field_type: "Integer",
      special: "Required (between 0 and 100)",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "current_level",
      field_type: "Integer",
      special: "To be calculated as trial data is collected, never input by the user (between 0 and 100)",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "metric_name",
      field_type: "Text",
      special: "Required",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "attempts_per_trial",
      field_type: "Integer",
      special: "How many questions to administer in a single sitting",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "number_of_trials",
      field_type: "Integer",
      special: "",
      table: subgoal_table._id
    }),
    TableProperty.create({
      field: "created_at",
      field_type: "Timestamp",
      special: "Required, autogenerated",
      table: subgoal_table._id
    }),
  ])


  // Task Table
  const task_table = await Table.create({name: "Task"});
  await Promise.all([
    TableProperty.create({
      field: "task_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: task_table._id
    }),
    TableProperty.create({
      field: "subgoal_id",
      field_type: "Unique ID",
      special: "References “subgoal”",
      table: task_table._id
    }),
    TableProperty.create({
      field: "assignee_id",
      field_type: "Unique ID",
      special: "References “user”",
      table: task_table._id
    }),
    TableProperty.create({
      field: "due_date",
      field_type: "Timestamp",
      special: "",
      table: task_table._id
    }),
    TableProperty.create({
      field: "trial_count",
      field_type: "Integer",
      special: "",
      table: task_table._id
    }),
    TableProperty.create({
      field: "seen",
      field_type: "True/False",
      special: "Required, default false",
      table: task_table._id
    }),
  ])


  // Trial Data Table
  const trial_data_table = await Table.create({name: "Trial Data"});
  await Promise.all([
    TableProperty.create({
      field: "trial_data_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: trial_data_table._id
    }),
    TableProperty.create({
      field: "task_id",
      field_type: "Unique ID",
      special: "References “task”",
      table: trial_data_table._id
    }),
    TableProperty.create({
      field: "created_by_user_id",
      field_type: "Unique ID",
      special: "References “user”",
      table: trial_data_table._id
    }),
    TableProperty.create({
      field: "success",
      field_type: "Integer",
      special: "Required",
      table: trial_data_table._id
    }),
    TableProperty.create({
      field: "unsuccess",
      field_type: "Integer",
      special: "Required",
      table: trial_data_table._id
    }),
    TableProperty.create({
      field: "submitted",
      field_type: "True/False",
      special: "Required, default false",
      table: trial_data_table._id
    }),
    TableProperty.create({
      field: "notes",
      field_type: "Text",
      special: "",
      table: trial_data_table._id
    }),
    TableProperty.create({
      field: "created_at",
      field_type: "Timestamp",
      special: "Required, autogenerated",
      table: trial_data_table._id
    }),
  ])


  // Trial Data File Table
  const trial_data_file_table = await Table.create({name: "Trial Data File"});
  await Promise.all([
    TableProperty.create({
      field: "trial_file_id",
      field_type: "Unique ID",
      special: "Required, autogenerated",
      table: trial_data_file_table._id
    }),
    TableProperty.create({
      field: "trial_data_id",
      field_type: "Unique ID",
      special: "References “trial_data”",
      table: trial_data_file_table._id
    }),
    TableProperty.create({
      field: "file_id",
      field_type: "Unique ID",
      special: "References “file”",
      table: trial_data_file_table._id
    }),
    TableProperty.create({
      field: "created_at",
      field_type: "Timestamp",
      special: "Required, autogenerated",
      table: trial_data_file_table._id
    }),
  ])

  // check
  const populated_tables = await Promise.all([
    user_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    paras_to_cms_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    account_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    session_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    student_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    file_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    iep_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    goal_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    subgoal_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    task_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    trial_data_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
    trial_data_file_table.populate({
      path: 'table_properties',
      select: 'field field_type special'
    }),
  
  ])

  console.log(JSON.stringify(populated_tables, null, 2));

}


async function seedIssues() {

  await Issue.deleteMany({});
  await UserStory.deleteMany({});

  const connor = await User.create({
    email: "connorwales@gmail.com",
    registered: true,
    active: true
  })

  const CM_CollectingDataStep1 = await Issue.create({
    name: "CM - Collecting Data Step 1",
    issueType: "page",
    description: "Step 1 in the desktop view of collecting data - outlining information to be known by CM or para in advance of data collection",
    type: "page",
    design_figma_link: "https://www.figma.com/design/m09znscRXNqSziAiEbNLTf/Compass-Designs?node-id=10411-66810&t=iwmoiYf1zfthSjMG-0",
    assigned_engineers: [connor._id],
    design_complete: true
  })

  console.log("issue created");

  const CM_CollectingDataStep1UserStories = await Promise.all([
    UserStory.create({
      issue: CM_CollectingDataStep1._id,
      description: [
        {
          textType: "string",
          text: "View the "
        },
        {
          textType: "tablePropertyRef",
          text: "Goal.created_at"
        }
      ],
    }),
    UserStory.create({
      issue: CM_CollectingDataStep1._id,
      description: [
        {
          textType: "string",
          text: "View the "
        },
        {
          textType: "tablePropertyRef",
          text: "Goal.description"
        }
      ],
    }),
    UserStory.create({
      issue: CM_CollectingDataStep1._id,
      description: [
        {
          textType: "string",
          text: "View the "
        },
        {
          textType: "tablePropertyRef",
          text: "Subgoal.materials"
        }
      ]
    }),
    UserStory.create({
      issue: CM_CollectingDataStep1._id,
      description: [
        {
          textType: "string",
          text: "View the "
        },
        {
          textType: "tablePropertyRef",
          text: "Subgoal.instructions"
        }
      ]
    }),
    UserStory.create({
      issue: CM_CollectingDataStep1._id,
      description: [
        {
          textType: "string",
          text: "View the "
        },
        {
          textType: "tablePropertyRef",
          text: "Subgoal.frequency"
        }
      ]
    }),
    UserStory.create({
      issue: CM_CollectingDataStep1._id,
      description: [
        {
          textType: "string",
          text: "Link to the "
        },
        {
          textType: "pageRef",
          text: "Edit Goal Page"
        },
      ]
    }),
    UserStory.create({
      issue: CM_CollectingDataStep1._id,
      description: [
        {
          textType: "string",
          text: "Have a button that clicks through to the "
        },
        {
          textType: "pageRef",
          text: "CM - Collecting Data Step 2"
        },
        {
          textType: "string",
          text: " page"
        }
      ]
    })
  ]);

  console.log("user stories created and assigned");

  // check
  const populated_issues = await getPopulatedIssues();
  console.log(JSON.stringify(populated_issues, null, 2));

  return;

}

async function run() {

  // mongoose setup
  dotenv.config({path: ".env.local"});
  await mongooseConnect();

  await seedTables();
  await seedIssues();

  await mongoose.disconnect();
}

run();













